# Generated by Django 5.2.5 on 2025-08-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_profile_usermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='imgg/profile_img.jpg', null=True, upload_to='profile_img/'),
        ),
    ]
