# Generated by Django 5.2.5 on 2025-08-25 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_liked_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_like', to='blog_app.blog'),
        ),
    ]
