# Generated by Django 5.2.5 on 2025-08-25 08:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_liked_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liked',
            unique_together={('user', 'post')},
        ),
    ]
