# Generated by Django 5.2.5 on 2025-08-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_blockuser_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, default=0, null=True, to='blog_app.tag'),
        ),
    ]
