# Generated by Django 5.2.5 on 2025-08-22 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_tag_album_gallery_blog_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='album',
        ),
        migrations.AddField(
            model_name='gallery',
            name='album',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='blog_app.album'),
        ),
    ]
