# Generated by Django 5.2.5 on 2025-08-22 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_remove_gallery_album_gallery_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='album',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='blog_app.album'),
        ),
    ]
